development:
  adapter: sqlite3
  database: meats.db
  pool: 30
  timeout: 6000

production:
  adapter: postgresql
  database: meat
  pool: 30
  timeout: 6000
  username: meat
  password: waves
  host: localhost:5432