development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 30
  timeout: 6000

production:
  adapter: postgresql
  database: meat
  pool: 50
  timeout: 12000
  username: meat
  password: waves
  host: localhost:5432